### PR TITLE
Possible fix for flaky test

### LINKED ISSUE #20: Fix flakey `ReceiveRoutedMessage` test

### PR DESCRIPTION
**Pull request by Ioana37**
The purpose of this PR is to propose a fix for the flaky test. Closes #20.

Apart from rearranging the test flow to increase readability, the main change is that I removed the line marked in this image.
tempsnip

Since making this change, I ran the test more than 50 times both in VS and VS Code and had no more failures.
However, I do not exactly understand what was the issue before. I assume that some sort of this disconnection occurs and the messages are lost. I tried to listen for a WILL message which might have proven an ungraceful disconnect, but there weren't any sent.

FINAL CONCLUSION
Creating another instance of the Device class with the same connection string and storing it in the same object leads to creating another instance of the MqttClient object which in some of the test runs appears to result in not receiving the message sent while the client is disconnected.

### CODE REVIEW

**Comment by vjrantal** [comment]
@Ioana37 With this fix, what kind of pass ratio you saw in your local test runs?

**Comment by Ioana37** [comment]
@vjrantal so far I did not have any fails in over 30 runs, but I am still cautiously optimistic.

**Review by vjrantal — COMMENTED** [review]
@Ioana37 If you would like to improve the commit, I think it would be useful if the commit message would describe what the root cause was and why this change address the problem.

**Comment by syedhassaanahmed** [comment]
@Ioana37 Before completing the PR, when you have time I'd like you to dig deeper into what happens in the removed line. Most likely the [Device Class Constructor](https://github.com/vjrantal/azure-iot-mqtt-features/blob/main/src/Device/Device.cs) does something that causes the flaky behavior.

**Comment by vjrantal** [comment]
@Ioana37 @syedhassaanahmed I would agree that I would like to understand the root cause before merging the fix.

**Review by syedhassaanahmed — APPROVED** [review]

File: src/Testing/MqttTests.cs [hunk 1]
```diff
@@ -101,31 +101,31 @@ public async Task ReceiveD2CMessageWithQosZero()
         [Test]
         public async Task ReceiveAllC2DMessagesWhileDisconnected()
         {
-            // Arrange
+            //Arrange
```
Comment (EliiseS) [inline src/Testing/MqttTests.cs]: Super duper nit: all other comments in the test have a space and I think it looks nicer with a space

File: src/Testing/MqttTests.cs [hunk 2]
```diff
@@ -101,31 +101,31 @@ public async Task ReceiveD2CMessageWithQosZero()
...
-            var firstPayload = Guid.NewGuid().ToString();
-            var secondPayload = Guid.NewGuid().ToString();
             var payloads = new ConcurrentBag<string>();
             Action<MqttApplicationMessageReceivedEventArgs> applicationMessageReceived = (MqttApplicationMessageReceivedEventArgs e) =>
             {
                 payloads.Add(e.ApplicationMessage.ConvertPayloadToString());
-            };
-
-            // Act
+            };
```
Comment (EliiseS) [inline src/Testing/MqttTests.cs:111]:
```suggestion
            };
            
            // Act & Assert
```

**Comment by EliiseS** [comment]
Do you think this fix is because of the `var factory = new MqttFactory();` in the constructor? I'd try this out by making it static

File: src/Testing/MqttTests.cs (hunk 1 above)
Comment (Ioana37) [reply src/Testing/MqttTests.cs]: Good catch, will fix it :)

**Comment by Ioana37** [comment]
@EliiseS, yes that appears to the issue, but still not clear about the underlying inner workings about the MQTT client so that is why I tried to listen for a Will message. It seems that creating another instance of the object occasionally results in a disconnection from the other instance. 
Was there any reason behind re-instantiating the device object in the test?

**Comment by EliiseS** [comment]
@Ioana37  If I recall correctly, I think it was because the testcase said the vehicle is shut down, so I thought reusing the same object wouldn't be a *real* shutdown. Something about being paranoid about it not *really* disconnecting.

But, I'm not sure that's a *real* concern, what do you think @vjrantal @syedhassaanahmed?

File: src/Testing/MqttTests.cs (hunk 2 above)
Comment (EliiseS) [reply src/Testing/MqttTests.cs:111]: I think you had a good point about the act and assert sections not making a sense, but to keep in convetion with the other tests, I thought this combined comment would be a good idea :)

Comment (Ioana37) [reply src/Testing/MqttTests.cs:111]: Yes, I agree, that's a good point!

**Comment by EliiseS** [comment]
Conclusions reached in a call, write up of the issue can be found above and PR merged as is :)
